#!/usr/bin/env python3

import os
import shutil
import subprocess
import sys

os.environ.setdefault("TASKCLUSTER_ROOT_URL", "https://community-tc.services.mozilla.com/")


def install(base, python):
    venv = os.path.join(base, ".venv")

    # Create a virtualenv if it doesn’t exist
    if not os.path.isdir(venv):
        exit_code = subprocess.call(["virtualenv", "-p", python, venv])
        if exit_code:
            sys.exit(exit_code)

    # Install requirements with pip, unless we already have
    requirements_file = os.path.join(base, "python-requirements")
    requirements = open(requirements_file).read()

    installed_file = os.path.join(venv, "installed-requirements")
    try:
        installed = open(installed_file).read()
    except OSError:
        installed = ""

    if installed != requirements:
        pip = os.path.join(venv, "bin", "pip")
        exit_code = subprocess.call([pip, "install", "-r", requirements_file])
        if exit_code:
            sys.exit(exit_code)
        shutil.copyfile(requirements_file, installed_file)

    return venv


def command_file(here, command):
    commands = os.path.join(here, "commands")
    command_file = os.path.join(commands, command + ".py")
    if not os.path.isfile(command_file):
        print("Usage: %s <command> [args]" % sys.argv[0])
        print()
        print("Commands:")
        for command in sorted(os.listdir(commands) + ["salt.py"]):
            if command.endswith(".py"):
                print("  " + command[:-len(".py")])
        sys.exit(1)
    return command_file


def run(command="help", *cli_args):
    here = os.path.abspath(os.path.dirname(__file__))

    if command == "salt":
        base = os.path.join(here, "salt")
        python = "python2"
        args = ["salt-ssh"]
    else:
        base = here
        python = sys.executable
        args = ["python", command_file(here, command)]

    venv = install(base, python)
    args[0] = os.path.join(venv, "bin", args[0])
    sys.exit(subprocess.call(args + list(cli_args), cwd=base))


if __name__ == "__main__":
    run(*sys.argv[1:])
