checkForNewDeploymentEverySecs: 120
idleTimeoutSecs: 14400
shutdownMachineOnIdle: True
workerTypeMetadata: {}

# These need to match ../windows/first-boot.ps1
ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
taskclusterProxyExecutable: C:\generic-worker\taskcluster-proxy.exe
livelogExecutable: C:\generic-worker\livelog.exe

# https://github.com/mozilla/community-tc-config/blob/8267df4/generate/workers.py#L225
sentryProject: generic-worker
wstAudience: communitytc
wstServerURL: https://community-websocktunnel.services.mozilla.com
