win2016:
    kind: aws_windows
    min_capacity: 1
    max_capacity: 10
    regions:
        us-west-2: ami-0707fecfddd0c8421
    capacity_per_instance_type:
        c5.xlarge: 1

# These are managed in
# https://github.com/mozilla/community-tc-config/blob/master/config/projects.yml
docker:
    kind: externally-managed
docker-untrusted:
    kind: externally-managed
