win2016-staging:
    kind: aws_windows
    min_capacity: 0
    max_capacity: 4
    regions:
        us-west-2: ami-027f1213323c74402
    capacity_per_instance_type:
        c5.xlarge: 1

# These are managed in
# https://github.com/mozilla/community-tc-config/blob/master/config/projects.yml
docker:
    kind: externally-managed
docker-untrusted:
    kind: externally-managed
