win2016:
    kind: aws_windows
    min_capacity: 1
    max_capacity: 10
    regions:
        us-west-2: ami-0f576580c89daf9e3
    capacity_per_instance_type:
        c5.2xlarge: 1

macos:
    kind: static
    worker_hostname_template: servo-tc-{id}.servo.org
    workers:
        # Use `macFOO: disabled` to stop a worker from picking up tasks
        # https://github.com/servo/servo/issues/24691
        mac1:
        mac2:
        mac3:
        mac4:
        mac5:
        mac6:
        mac7:
        mac8:
        mac9:

# These are managed in
# https://github.com/mozilla/community-tc-config/blob/master/config/projects.yml
docker:
    kind: externally-managed
docker-untrusted:
    kind: externally-managed
